# Generated by Django 3.2.8 on 2021-10-10 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('numeroIdentificacion', models.CharField(max_length=20, verbose_name='Numero_Identificacion')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre_Completo')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('numero_contacto', models.CharField(max_length=20, verbose_name='Numero_Contacto')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('edad', models.IntegerField(default=0)),
                ('resutado_prueba', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(default=0)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_adopciones', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('respuesta', models.CharField(max_length=50, verbose_name='Respuesta')),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id_Candidatos', to='appAdopciones.candidatos')),
                ('mascotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id_Mascotas', to='appAdopciones.mascotas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
