# Generated by Django 3.2.8 on 2021-10-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='disponibilidad',
            new_name='Disponibilidad',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='edad',
            new_name='Edad',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='id_mascota',
            new_name='Id_Mascota',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
