# Generated by Django 3.2.8 on 2021-10-10 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0003_auto_20211009_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='Id_Solicitud',
            new_name='id_Solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Id_Mascotas',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Id_Mndidatos',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Id_User',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='0', max_length=20, verbose_name='estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_Candidatos',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='id_Candidatos', to='appAdopciones.candidatos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_Mascotas',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='id_Mascotas', to='appAdopciones.mascotas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_User',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='appAdopciones.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='respuesta',
            field=models.CharField(default='0', max_length=50, verbose_name='respuesta'),
            preserve_default=False,
        ),
    ]
