# Generated by Django 3.2.8 on 2021-10-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0004_auto_20211010_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='Id_Candidato',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Id_Mascota',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_Solicitud',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
