# Generated by Django 3.2.8 on 2021-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0005_auto_20211011_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='Id_Candidato',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Id_Mascota',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_Solicitud',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
