# Generated by Django 3.2.8 on 2021-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0006_auto_20211011_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='Id_Candidato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Edad',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Id_Mascota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_Solicitud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
