# Generated by Django 3.2.8 on 2021-10-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0007_auto_20211011_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatos',
            old_name='Resutado_Prueba',
            new_name='Resultado_Prueba',
        ),
    ]
