# Generated by Django 3.2.8 on 2021-10-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0008_rename_resutado_prueba_candidatos_resultado_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='Edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='Resultado_Prueba',
            field=models.IntegerField(verbose_name='Resultado_Prueba'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
