# Generated by Django 3.2.8 on 2021-10-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0009_auto_20211013_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='Disponibilidad',
            field=models.BooleanField(verbose_name='Disponibilidad'),
        ),
    ]
