# Generated by Django 3.2.8 on 2021-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0010_alter_mascotas_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='Afrontar_Problemas',
            field=models.CharField(max_length=2, null=True, verbose_name='Afrontar_Problemas'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='Has_Tenido_Mascotas',
            field=models.CharField(max_length=2, null=True, verbose_name='Ha_Tenido_Mascotas'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='Recursos_Economicos',
            field=models.CharField(max_length=2, null=True, verbose_name='Recursos_Economicos'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='Seras_Responsable',
            field=models.CharField(max_length=2, null=True, verbose_name='Seras_Responsable'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='Tienes_Espacio',
            field=models.CharField(max_length=2, null=True, verbose_name='Tienes_Espacio'),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='Tienes_Tiempo',
            field=models.CharField(max_length=2, null=True, verbose_name='Tienes_Tiempo'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='Resultado_Prueba',
            field=models.IntegerField(default=False, verbose_name='Resultado_Prueba'),
        ),
    ]
